// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSession = "sessions"

// Session mapped from table <sessions>
type Session struct {
	ID              string    `gorm:"column:id" json:"id"`
	UserID          int32     `gorm:"column:user_id" json:"user_id"`
	MaxAge          int32     `gorm:"column:max_age" json:"max_age"`
	Deleted         bool      `gorm:"column:deleted" json:"deleted"`
	CreateUser      string    `gorm:"column:create_user" json:"create_user"`
	CreateTimestamp time.Time `gorm:"column:create_timestamp" json:"create_timestamp"`
	UpdateUser      string    `gorm:"column:update_user" json:"update_user"`
	UpdateTimestamp time.Time `gorm:"column:update_timestamp" json:"update_timestamp"`
}

// TableName Session's table name
func (*Session) TableName() string {
	return TableNameSession
}
